services:
  joplin:
    image: joplin/server:3.0.1-beta
    restart: unless-stopped
    environment:
      - APP_PORT=80
      - APP_BASE_URL=https://joplin-server.${TAILNET}.ts.net
  nginx:
    image: nginx:1.27.0
    volumes:
      - ./nginx-2.conf:/etc/nginx/nginx.conf
      - tls:/mnt/tls:ro
    restart: unless-stopped
    network_mode: service:tailscale
  tailscale:
    image: tailscale/tailscale:v1.72.1
    volumes:
      - tailscale:/var/run/tailscale
      - tls:/mnt/tls
    environment:
      - TS_HOSTNAME=joplin-server
      - TS_STATE_DIR=/var/run/tailscale
    restart: unless-stopped
volumes:
  tailscale:
  tls:
